image: docker:latest

variables:
  CONTAINER_TEST_IMAGE: ${REGISTRY}/${CI_PROJECT_NAME}:${CI_BUILD_REF_NAME}_${CI_BUILD_REF}_test
  CONTAINER_RELEASE_IMAGE: ${REGISTRY}/${CI_PROJECT_NAME}:${CI_BUILD_REF_NAME}_${CI_BUILD_REF}

stages:
  - build
  - release

before_script:
  - docker info

build:
  stage: build
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker build --rm -t $CONTAINER_TEST_IMAGE .

release:
  stage: release
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
