image: docker:latest

variables:
  IMAGE_TAG: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}
  CONTAINER_RELEASE_IMAGE: ${REGISTRY}/${CI_PROJECT_NAME}:${CI_BUILD_TAG}

stages:
  - build
  - release

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - echo "Building $IMAGE_TAG"
    - docker build --rm -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

release:
  stage: release
  only:
    - tags
  script:
    - echo "Building $CONTAINER_RELEASE_IMAGE"
    - docker pull $IMAGE_TAG
    - docker tag $IMAGE_TAG $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
